### ISSUE TITLE
HTTP 404 Error: Model Download Link Broken in ArcFace Implementation

### ISSUE THREAD

**Issue by JcHuang11234** [mobilesec/arcface-tensorflowlite#11]
Hi , I hope this message finds you well!

Thank you for providing this helpful package.

I encountered an issue while trying to use the ArcFace package. When initializing the ArcFace class, the code attempts to download the TensorFlow Lite model from the following URL: https://cloud.ins.jku.at/index.php/s/g2YDT8Zn9RkzsEy/download. However, this link returns a 404 error, indicating that the file is no longer available.

Error Details: Here's the traceback I received:

HTTPError: HTTP Error 404: Not Found

This error occurs in the ArcFace.py file at line 35 when the code attempts to download the model using the download_file function from the astropy.utils.data module.

Could you please provide an updated URL for the model file? Alternatively, is there a way to manually download the model and provide its path during initialization?

Thank you for your assistance, and I look forward to your guidance on how to resolve this issue!

**Comment by michaelroland** [comment]
See #8
