### ISSUE TITLE
REQUEST: TFLITE 

### ISSUE THREAD

**Issue by marwenbk** [mobilesec/arcface-tensorflowlite#7]
Can you provide us with the pre-trained tflite model ?

**Comment by p-hofer** [comment]
The pre-trained tflite model is downloaded automatically if it's not found (https://github.com/mobilesec/arcface-tensorflowlite/blob/master/arcface/ArcFace.py#L35), here is the link to the .tflite file: https://cloud.ins.jku.at/index.php/s/g2YDT8Zn9RkzsEy/download
